//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelExport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCertificate
    {
        public int SrNo { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public int EmployeeNumber { get; set; }
        public string NomineeName { get; set; }
        public string NomineeRelationship { get; set; }
    }
}
